//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIGORANDEY_AVTOSERVIS.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class name_databaseEntities : DbContext
    {
        public static name_databaseEntities _context;

        public name_databaseEntities()
            : base("name=name_databaseEntities")
        {
        }

        private static name_databaseEntities GetContext()
        {
            if (_context == null)
                _context = new name_databaseEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<order> order { get; set; }
        public DbSet<orderuserlist> orderuserlist { get; set; }
        public DbSet<shift> shift { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<userlist> userlist { get; set; }
        public DbSet<userrole> userrole { get; set; }
    }
}
