//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIGORANDEY_AVTOSERVIS.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift
    {
        public shift()
        {
            this.userlist = new HashSet<userlist>();
        }
    
        public int shiftid { get; set; }
        public System.DateTime datestart { get; set; }
        public System.DateTime dateend { get; set; }
    
        public virtual ICollection<userlist> userlist { get; set; }
    }
}
