//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIGORANDEY_AVTOSERVIS.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.orderuserlist = new HashSet<orderuserlist>();
            this.userlist = new HashSet<userlist>();
        }
    
        public int userid { get; set; }
        public string Login { get; set; }
        public string password { get; set; }
        public string status { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public int userroleid { get; set; }
    
        public virtual ICollection<orderuserlist> orderuserlist { get; set; }
        public virtual userrole userrole { get; set; }
        public virtual ICollection<userlist> userlist { get; set; }
    }
}
