//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIGORANDEY_AVTOSERVIS.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class userrole
    {
        public userrole()
        {
            this.user = new HashSet<user>();
        }
    
        public int userroleid { get; set; }
        public string namerole { get; set; }
    
        public virtual ICollection<user> user { get; set; }
    }
}
